app/models/comment.rb, app/models/guest.rb, app/models/item.rb, app/models/task.rb, app/models/trip.rb, app/models/user.rb, app/models/vote.rb, config/puma.rb, db/migrate/20201119134015_create_trips.rb, db/migrate/20201119134024_create_guests.rb, db/migrate/20201119134031_create_tasks.rb, db/migrate/20201119134044_create_items.rb, db/migrate/20201119134055_create_votes.rb, db/migrate/20201119134104_create_comments.rb, db/schema.rb, test/models/comment_test.rb, test/models/guest_test.rb, test/models/item_test.rb, test/models/task_test.rb, test/models/trip_test.rb, test/models/vote_test.rb
- created models in order 
1. Trips
2. Guests
3. Tasks
4. Items
5.Votes
6.Comments
=> Created all models

app/models/flight_detail.rb, app/models/item.rb, app/models/task.rb, app/models/trip.rb, app/models/user.rb, db/migrate/20201119134044_create_items.rb, db/migrate/20201124122924_create_flight_details.rb, db/migrate/20201124123625_create_tasks.rb, db/schema.rb, test/models/airline_test.rb, test/models/flight_detail_test.rb
Updated the models with latest DB
=> updated the models

app/controllers/uikits_controller.rb, app/views/uikits/index.html.erb, config/routes.rb, test/controllers/uikit_controller_test.rb
Created UI kit where we will have all of our components design
=>  created UIkit page for all UI design

app/controllers/trips_controller.rb, app/views/trips/_form.html.erb, app/views/trips/edit.html.erb, app/views/trips/index.html.erb, app/views/trips/new.html.erb, app/views/trips/show.html.erb, config/routes.rb, db/migrate/20201124140907_add_name_to_trip.rb, db/schema.rb, test/controllers/trips_controller_test.rb
add trips controller
add routes for CRUD
add links between views
in addition, add 'name' to the trip model
=> Trips controller

Gemfile, Gemfile.lock, db/seeds.rb
- seeds for user creation & Trip creation
=> created seeds for trip

app/views/trips/show.html.erb
to ease our testing phase, I added an 'edit' button on the show page. 
the edit and new pages use the same _form.html.erb
=> add edit function on show page for testing purpose

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/trips_controller.rb, app/policies/application_policy.rb, app/policies/trip_policy.rb, test/policies/trip_policy_test.rb
I added pundit but I'm not 100% sure there will not be conflict with my previous PR, adding the Edit button. 
let me know if it needs adjustment after the merge of the previous PR.
=> added pundit

.gitignore, app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/models/user.rb, app/views/trips/show.html.erb, app/views/user_mailer/welcome.html.erb, app/views/user_mailer/welcome.text.erb, config/environments/development.rb, config/environments/production.rb, config/initializers/smtp.rb, db/schema.rb, db/seeds.rb, test/mailers/previews/user_mailer_preview.rb, test/mailers/user_mailer_test.rb
For testing:-
-------------
1. Ask me for the app password, which needs to configure in .env file
GMAIL_ADDRESS=traveltogether453@gmail.com
GMAIL_APP_PASSWORD=*****
2. Signup using your email address, you will receive an email like below
=> Implemented welecome email message

app/assets/stylesheets/components/_action_cards.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tags.scss, app/views/uikits/index.html.erb, db/schema.rb
- Created all UI Kit Design 
- Created NavBar
- All designs are components
=> UI Kit complete with component design

Gemfile, Gemfile.lock, app/controllers/trips_controller.rb, app/views/trips/index.html.erb
- applied trip card template for the view.
**Note:- please ask me for the api key before you do test**.
=> Placesapi integration

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_tabs.scss, app/controllers/items_controller.rb, app/javascript/controllers/hello_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/item_status_controller.js, app/javascript/packs/application.js, app/models/item.rb, app/policies/item_policy.rb, app/views/items/_item.html.erb, app/views/items/_items.html.erb, app/views/items/index.html.erb, app/views/trips/show.html.erb, config/routes.rb, db/migrate/20201128061236_add_item_type_to_items.rb, db/schema.rb, db/seeds.rb, package.json, test/controllers/items_controller_test.rb, test/policies/item_policy_test.rb, yarn.lock
Added items controller with index action and route
Updated items schema => added category
Added ability to filter items listings based on Category (Flights, Accomms, Activities) and status (Pending, Approved, Booked)
Added some item seeds
Note:
May need refactoring on the code in stimulus controller and javascript.js - looks bloated - do it after we finish all core features for the site
=> Filter function 

app/assets/stylesheets/components/_footer.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/uikits/index.html.erb
- small modification to add the footer to every page and remove the navbar from lewagon
-UI kit also updated
=>  added footer to all pages and made it sticky

db/migrate/20201128085805_rename_item_type_to_category.rb, db/schema.rb
remove duplicate migration file.
Remember to rerun your migrations
=> remove duplicate migration file

app/controllers/messages_controller.rb, app/controllers/trips_controller.rb, app/models/message.rb, app/models/trip.rb, app/policies/message_policy.rb, app/views/trips/show.html.erb, config/routes.rb, db/migrate/20201128062444_create_messages.rb, db/schema.rb, test/controllers/messages_controller_test.rb, test/models/message_test.rb
Basic chatting feature implemented.
- Now you can chat with your friends on the trip show page!
Note:
- ActionCable NOT YET enabled
- Front-end Needs improvement
=> chat functioning

app/assets/stylesheets/components/_action_cards.scss, app/assets/stylesheets/components/_index.scss, app/controllers/items_controller.rb, app/javascript/controllers/item_status_controller.js, app/javascript/packs/application.js, app/views/items/_items.html.erb, app/views/trips/show.html.erb
Removed redundant partials for items listings
Changed status filter (pending, approved, booked) to checkbox type
added dropdown button and status filter is now inside the dropdown window
=> added dropdown for status filter

app/assets/stylesheets/application.scss, app/javascript/controllers/item_form_controller.js, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/items/_form_accomodation.html.erb, app/views/items/_form_activity.html.erb, app/views/items/_form_flight.html.erb, app/views/trips/_form.html.erb, app/views/trips/show.html.erb, db/schema.rb, package.json, yarn.lock
- Enable datepickr
- Disabled past date.
=> Date picker

app/models/item.rb, db/seeds.rb
corrected typo that was causing accommodation items not seeding
update seed
=> fix typo and update seed

Gemfile, Gemfile.lock, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js
=> Flatflikr bug

app/controllers/items_controller.rb, app/javascript/controllers/item_form_controller.js, app/models/item.rb, app/views/items/_form_Accommodation.html.erb, app/views/items/_form_activity.html.erb, app/views/items/_form_flight.html.erb, app/views/trips/show.html.erb
align the naming convention for status (Flight, Accommodation and Activity) that is causing bug in item creation
=> Create items bug

app/views/trips/show.html.erb
remove duplicate create item button
=> remove duplicate create button

app/views/trips/show.html.erb
selector for new item (flight, accomodation, activity) has been renamed by mistake. 
changing back the name to give access to this function.
=> add back the add item selector

app/views/items/_item.html.erb
=> status update dynamically

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_voting.scss, app/controllers/items_controller.rb, app/controllers/trips_controller.rb, app/controllers/votes_controller.rb, app/javascript/controllers/vote_controller.js, app/models/item.rb, app/policies/vote_policy.rb, app/views/items/_item.html.erb, app/views/trips/show.html.erb, app/views/uikits/index.html.erb, config/routes.rb, db/seeds.rb, test/controllers/votes_controller_test.rb, test/policies/vote_policy_test.rb
Fix some front-end bugs in the item listing page. Some missing divs that cause items to be hidden in the view
built partial voting-system. 90% complete. need to resolve some bugs
=> Fix-frontend-bug / Voting system

app/controllers/messages_controller.rb, app/javascript/channels/trip_channel.js, app/views/trips/show.html.erb
Also it's now placed at the bottom of the trip show page
=> chat appear in reverse chronological order

app/controllers/trips_controller.rb, app/mailers/trip_mailer.rb, app/policies/trip_policy.rb, app/views/trip_mailer/share.html.erb, app/views/trip_mailer/share.text.erb, app/views/trips/email.html.erb, app/views/trips/share.html.erb, app/views/trips/show.html.erb, config/environments/development.rb, config/routes.rb, test/mailers/previews/trip_mailer_preview.rb, test/mailers/trip_mailer_test.rb
- trip sharing invitation finished
=> Email trip sharing

app/assets/stylesheets/components/_action_cards.scss, app/views/items/_item.html.erb, app/views/uikits/index.html.erb
- fixed the accommodation card problem 
- moved down heart by .5px to align better
=>  fixed action cards problem

app/views/items/_item.html.erb
forget to apply voting system to all item cards
=> apply voting system for all

app/views/items/_item.html.erb, app/views/uikits/index.html.erb
activity item listing front end fix
=> fixed item listing frontend bug

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_voting.scss
- updated the image paths to work on Heroku 
-->  background-image: url(asset_path("banner2.jpg"))
=>  image paths updates

app/controllers/items_controller.rb, app/models/item.rb, app/views/items/_form_Flight.html.erb, app/views/items/_item.html.erb, db/migrate/20201205080925_add_default_value_to_item_status.rb, db/migrate/20201205081112_delete_column_type_for_items.rb
fix but when creating new flight
migrations
- add default value 'pending' when creating items
- remove column 'type' from items
=> New flight

app/views/items/_item.html.erb, db/schema.rb, db/seeds.rb
- added start & end date for flight in seed
- fixed some bug in index html file.
=> fixed db seed & item_flight html file

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cardTrip.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_banner.html.erb, app/views/trips/index.html.erb
- improved the look of trips index page
=>  improved the front end of trips index

app/assets/stylesheets/components/_action_cards.scss, app/assets/stylesheets/components/_buttons.scss, app/views/items/_item.html.erb
- fix for flight cards 
- made some minor improvements to the front end of action cards
=>  fixed flight card front end and changed some look and feel

app/controllers/trips_controller.rb, app/views/trips/index.html.erb, app/views/trips/show.html.erb, db/schema.rb, db/seeds.rb
- traveller avatar added.
- email form adjusted.
- removed the cancel button under the email form.
=> traveller avatar added

config/environments/development.rb, config/environments/test.rb, config/storage.yml
=> Traveller avatar

app/controllers/items_controller.rb, app/policies/item_policy.rb, app/views/items/_item.html.erb, config/routes.rb
change update action in items controller to update_to_booked
=> Change method name

app/controllers/items_controller.rb, app/policies/item_policy.rb
- pundit policy has been created for items.
=> fixed pundit for creating items

app/assets/stylesheets/components/_action_cards.scss, app/views/items/_item.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb
- Created Drop down menus for Index Trips ( Edit, Remove, Share)
- Created Drop down menus for Show Trips ( Edit, Remove)
All that is left is to add the links once ready from controller
=> created the elipsis buttons for all pages

app/views/trips/edit.html.erb, app/views/trips/index.html.erb
- Enabled edit and delete functionality on index page.
=> added edit and delete functionality for trip

app/views/trips/show.html.erb
- fixed delete functionality for trip items.
=> fixed delete functionality for trip items

app/views/trips/index.html.erb, db/seeds.rb
- fixed html to display for the past trips.
- added seeds for past trips.
=> finished past trips

app/controllers/items_controller.rb, app/javascript/controllers/item_status_controller.js, app/javascript/packs/application.js, app/views/trips/show.html.erb
Fix bug where the status filter is not working
adjustment: when "Itinerary" Tab is clicked, only "Booked" checkbox in the filter dropdown should be ticked
adjustment: when "Itinerary" Tab is clicked, the items displayed should be in ascending order in terms of start date
=> Status filter bug

Gemfile, Gemfile.lock, app/controllers/trips_controller.rb, app/javascript/packs/application.js, app/views/trips/invite.html.erb
added feature such that you can click a button to copy invite link to clipboard
=> Copy invite link to clipboard

app/controllers/items_controller.rb, app/controllers/trips_controller.rb, app/javascript/packs/application.js, app/models/flight_detail.rb, app/models/item.rb, app/policies/item_policy.rb, app/policies/trip_policy.rb, app/views/items/_form_Flight.html.erb, app/views/items/_item.html.erb, app/views/messages/_message.html.erb, app/views/shared/_footer.html.erb, app/views/trips/show.html.erb
fix bug that show javascript error in console
Added pundit for guests
- trip guests cannot see confirm item button
- only trip owner and guests can create item
- only item creator and trip owner can see the the ellipsis button for edit/delete item
added some validation for items and flight_details
render :new when form input failed validation
=> General bug fixes

app/javascript/controllers/tag_controller.js, app/views/items/_item.html.erb
confirm button will be disabled when pressed.
If item is booked status, confirm button will be disabled
remove browser alert prompt when deleting an item
=> Confirm button fix

Gemfile.lock, app/assets/stylesheets/components/_cardTrip.scss, app/assets/stylesheets/components/_cardTripPast.scss, app/views/trips/index.html.erb
=> created past trips cards according to UI kit

Gemfile.lock, app/views/items/edit.html.erb
- fixed the bug for editing the flight details.
=> fixed bug for editing flight

app/controllers/landing_controller.rb
when u log in from landing page, it will route you to the trips page
=> fixed bug during login

app/assets/stylesheets/components/_action_cards.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_showTop.scss, app/views/trips/show.html.erb
aligned status filter with category filter but the cant get the dropdown to shift to the left. Need some help
=> align filter button with category filters
